Add SubMenu API and checkable items
vaadin/vaadin-context-menu-flow pull request #36
Opened 2018-12-21 12:48 UTC by pekam

New features:
- Get `SubMenu` API from a parent item with `MenuItem::getSubMenu`
- Create hierarchical menus by adding items and components to `SubMenus`
- Toggle checkmark on an item by clicking after calling `menuItem.setCheckable(true)`

Breaking changes:
- Behavior change: Clicking a non-item component inside the overlay doesn't close the overlay anymore. The overlay closes by clicking a `MenuItem` or outside the overlay.
- `ContextMenuBase` is now `abstract` and has type parameters. This shouldn't affect most users, as it's just a base class for `ContextMenu` and `GridContextMenu`.

The version is bumped to 2.0 because of the breaking changes.

Explaining some implementation details:
- `SubMenuBase` exists for the same reason as `ContextMenuBase`: to allow `SubMenu` and `GridSubMenu` extend this base class with different APIs.
- `ContextMenu` and `SubMenu` have a lot of common API, but `SubMenu` is not actually a `Component`, and it can't implement `HasComponents` (because that extends `HasElement`), which is why some `ContextMenuBase` API needs to be duplicated in `SubMenuBase`.
- The new client-side `items`-array is used now, which is why the children are moved inside virtual containers. Each `ContextMenu` and `SubMenu` has its own virtual container. The client-side connector finds those containers by their node-ids to populate the element instances inside them into the `items`-array.
- Because the `ContextMenu` and `SubMenu` can't have a common super-class maintaining the children-state, a `MenuContent` helper object is used by both of them to handle this common logic.
- `MenuItems` for `Grid` need to have `Grid`-specific API now, which is why `MenuItemBase` is introduced as the super-class for `MenuItem` and `GridMenuItem`.

The branch for updated `GridContextMenu` based on these changes can be seen here: https://github.com/vaadin/vaadin-grid-flow/compare/nested-context-menu

2018-12-21 12:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/vaadin-context-menu-flow?pullRequest=36) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/vaadin-context-menu-flow?pullRequest=36) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/vaadin-context-menu-flow?pullRequest=36) it.</sub>

2018-12-21 12:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/vaadin-context-menu-flow?pullRequest=36) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/vaadin-context-menu-flow?pullRequest=36) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/vaadin-context-menu-flow?pullRequest=36) it.</sub>

2018-12-21 14:58 UTC, pekam commented
The build failure should be fixed by https://github.com/vaadin/flow-component-base/pull/123

2018-12-21 16:42 UTC, pleku commented
Breaking changes seem minor, but need to be listed clearly in release notes.

2019-01-02 09:19 UTC, caalador commented
Build still fails after merged base PR 123 with:
```
java.lang.AssertionError: expected:<3> but was:<2>
	at com.vaadin.flow.component.contextmenu.it.ContextMenuDemoIT.hierarchicalContextMenu_openSubMenus(ContextMenuDemoIT.java:94)
```

2019-01-04 13:30 UTC, bogdanudrescu requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36)* status: 0 of 21 files reviewed, 7 unresolved discussions (waiting on @vaadin-bot and @pekam)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 36 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36#-LVO0x1J9Uc6p9-H9Ns5:-LVO0x1J9Uc6p9-H9Ns6:b-tqownc) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/54df5132d2205f5a9ce654282084b3121c5a2fb5/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L36)):*
> ```Java
>     public ContextMenu() {
>         super();
>         menuContent = new MenuContent<>(this, MenuItem::new,
> ```

Do you think we could lazy create this and hide it from direct usage? The reason I see is that any other subclass of ContextMenuBase which wants to use features of ContextMenuBase internally using menuContent ought to know to create it itself. Even if it's protected and we could add specific doc for it (which we don't have it yet) it would be simpler for the subclass now to care about.
___
*[src/main/java/com/vaadin/flow/component/contextmenu/MenuContent.java, line 48 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36#-LVNu7_j26z5VecGt7eo:-LVNu7_j26z5VecGt7ep:bafb0s2) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/54df5132d2205f5a9ce654282084b3121c5a2fb5/src/main/java/com/vaadin/flow/component/contextmenu/MenuContent.java#L48)):*
> ```Java
>     private C menu;
>     private SerializableFunction<C, I> itemGenerator;
>     private SerializablePredicate<Component> instanceOfItemPredicate;
> ```

What would be the case when instanceOfItemPredicate is something else than MenuItem.class::isInstance?
___
*[src/main/java/com/vaadin/flow/component/contextmenu/MenuContent.java, line 53 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36#-LVNuTl22gKAFHue2R_A:-LVNuTl22gKAFHue2R_B:b-fmaxmz) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/54df5132d2205f5a9ce654282084b3121c5a2fb5/src/main/java/com/vaadin/flow/component/contextmenu/MenuContent.java#L53)):*
> ```Java
>     private List<Component> children = new ArrayList<>();
> 
>     MenuContent(C menu, SerializableFunction<C, I> itemGenerator,
> ```

Could we add an overload without the function and predicate? And use MenuItem::new and MenuItem.class::isInstance as defaults, since only this is needed at the moment.
___
*[src/main/java/com/vaadin/flow/component/contextmenu/MenuItem.java, line 36 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36#-LVNwO0b-UcKx9AH342A:-LVNwO0c1rINT5mV17GD:be0bpnb) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/54df5132d2205f5a9ce654282084b3121c5a2fb5/src/main/java/com/vaadin/flow/component/contextmenu/MenuItem.java#L36)):*
> ```Java
>         super(contextMenu);
>         assert contextMenu != null;
>         this.subMenu = new SubMenu(this);
> ```

Could we have this lazy only when needed? 

One other suggestion would be that instead of leaving to MenuItem the responsibility for being a parent, we could have a Menu extends MenuItem to provide the SubMenu support, whatever that might be.


<!-- Sent from Reviewable.io -->

2019-01-22 13:27 UTC, denis-anisimov approved these changes
> Reviewed 19 of 21 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36)* status: all files reviewed, 7 unresolved discussions (waiting on @pekam and @vaadin-bot)



<!-- Sent from Reviewable.io -->

2019-01-22 13:27 UTC, denis-anisimov approved these changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36)* status: all files reviewed, 7 unresolved discussions (waiting on @pekam and @vaadin-bot)



<!-- Sent from Reviewable.io -->

2019-01-28 10:51 UTC, denis-anisimov reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36)* status: 8 of 22 files reviewed, 7 unresolved discussions (waiting on @bogdanudrescu, @caalador, @denis-anisimov, and @vaadin-bot)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 36 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36#-LVO0x1J9Uc6p9-H9Ns5:-LXJ2VFuChOXuz84qQxL:b-9foar2) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/54df5132d2205f5a9ce654282084b3121c5a2fb5/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L36)):*
<details><summary><i>Previously, bogdanudrescu (Bogdan Udrescu) wrote…</i></summary><blockquote>

Do you think we could lazy create this and hide it from direct usage? The reason I see is that any other subclass of ContextMenuBase which wants to use features of ContextMenuBase internally using menuContent ought to know to create it itself. Even if it's protected and we could add specific doc for it (which we don't have it yet) it would be simpler for the subclass now to care about.
</blockquote></details>

Redone.
Now the necessity of the menu manager creation is a part of contract. Subclass may not avoid it.
___
*[src/main/java/com/vaadin/flow/component/contextmenu/MenuItem.java, line 36 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36#-LVNwO0b-UcKx9AH342A:-LXJ2fTH6p1YPkX-m8ct:b-gnuie8) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/54df5132d2205f5a9ce654282084b3121c5a2fb5/src/main/java/com/vaadin/flow/component/contextmenu/MenuItem.java#L36)):*
<details><summary><i>Previously, bogdanudrescu (Bogdan Udrescu) wrote…</i></summary><blockquote>

Could we have this lazy only when needed? 

One other suggestion would be that instead of leaving to MenuItem the responsibility for being a parent, we could have a Menu extends MenuItem to provide the SubMenu support, whatever that might be.
</blockquote></details>

It's lazy now.
___
*[src/main/java/com/vaadin/flow/component/contextmenu/MenuContent.java, line 48 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36#-LVNu7_j26z5VecGt7eo:-LXJ2lST-H0Yt_05jZNO:b-uo8ah3) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/54df5132d2205f5a9ce654282084b3121c5a2fb5/src/main/java/com/vaadin/flow/component/contextmenu/MenuContent.java#L48)):*
<details><summary><i>Previously, bogdanudrescu (Bogdan Udrescu) wrote…</i></summary><blockquote>

What would be the case when instanceOfItemPredicate is something else than MenuItem.class::isInstance?
</blockquote></details>

The predicate usage was wrong.
The logic allowed to filter out any component and get components in the result. But the predicate is used to filter `MenuItemBase` which are represented by type `I`.
As a result it can't be an arbitrary predicate. The filter should keep only instance of type `I`.

The usage as I understand to have another type than `MenuItem`  which will be used with `Grid`.
___
*[src/main/java/com/vaadin/flow/component/contextmenu/MenuContent.java, line 53 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36#-LVNuTl22gKAFHue2R_A:-LXJ3L369ZY1lqnTSo-w:b-e53wtb) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/54df5132d2205f5a9ce654282084b3121c5a2fb5/src/main/java/com/vaadin/flow/component/contextmenu/MenuContent.java#L53)):*
<details><summary><i>Previously, bogdanudrescu (Bogdan Udrescu) wrote…</i></summary><blockquote>

Could we add an overload without the function and predicate? And use MenuItem::new and MenuItem.class::isInstance as defaults, since only this is needed at the moment.
</blockquote></details>

Predicate is removed.
I've not rewritten the logic except that.
As I understand the parameters are needed to support context menu in `Grid` case.
`MenuManager` is quite internal class so I don't see significant reason to reduce a number of arguments now since they are really needed.


<!-- Sent from Reviewable.io -->

2019-01-28 12:46 UTC, caalador requested changes
> Reviewed 1 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36)* status: 9 of 22 files reviewed, 7 unresolved discussions (waiting on @bogdanudrescu, @caalador, @denis-anisimov, @pekam, and @vaadin-bot)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/MenuItemBase.java, line 42 at r4](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36#-LXJU3dHCt8bcO3si9Ja:-LXJU3dI5orpFukMDMdp:b5l9mlh) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/6502441399fb6fdb6b82a6f9fb56d8b33a847c75/src/main/java/com/vaadin/flow/component/contextmenu/MenuItemBase.java#L42)):*
> ```Java
> @Tag("vaadin-item")
> @HtmlImport("frontend://bower_components/vaadin-item/src/vaadin-item.html")
> public abstract class MenuItemBase<C extends ContextMenuBase<C, I, S>, S extends SubMenuBase<C, I, S>, I extends MenuItemBase<C, S, I>>
> ```

Why does the MenuItemBase differ with the generics going `C,S,I` from all the rest that go `C,I,S `?
Also the params are defined in the order C,I,S not C,S,I


<!-- Sent from Reviewable.io -->

2019-01-28 12:53 UTC, denis-anisimov reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36)* status: 9 of 22 files reviewed, 7 unresolved discussions (waiting on @bogdanudrescu, @caalador, @denis-anisimov, @pekam, and @vaadin-bot)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/MenuItemBase.java, line 42 at r4](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36#-LXJU3dHCt8bcO3si9Ja:-LXJWJOfCtMePl3fAfq1:b-i9k0ve) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/6502441399fb6fdb6b82a6f9fb56d8b33a847c75/src/main/java/com/vaadin/flow/component/contextmenu/MenuItemBase.java#L42)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Why does the MenuItemBase differ with the generics going `C,S,I` from all the rest that go `C,I,S `?
Also the params are defined in the order C,I,S not C,S,I
</blockquote></details>

Good question for the original author.

Done.


<!-- Sent from Reviewable.io -->

2019-01-28 13:13 UTC, caalador approved these changes
> Reviewed 8 of 21 files at r1, 8 of 14 files at r4, 5 of 5 files at r5.
> Dismissed @bogdanudrescu from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36)* status: all files reviewed, 2 unresolved discussions (waiting on @pekam and @vaadin-bot)



<!-- Sent from Reviewable.io -->

2019-01-28 13:44 UTC, pleku approved these changes
> Dismissed @vaadin-bot from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pekam)



<!-- Sent from Reviewable.io -->

2019-01-28 13:47 UTC, merged